### ISSUE TITLE
Add compatibility to general probability distribution

### ISSUE THREAD

**Issue by cosminmarina** [eugenioLR/metaheuristic-designer#53]
What I mean by this is, one of the following options:

- Make some kind of compatibility with `scipy.stats` distribution, in order to specify by a parameter wich `scipy.stats` to use. For example: `which_pdf = foldcauchy` will search if `scipy.stats.fouldcauchy` distribution exist and, if yes, it will use its `rvs`, `pdf` or other methods.
- Provide some own-created distribution, builded as a `scipy.stats` pdf class.

**Comment by eugenioLR** [comment]
The new changes made in pull request #63 adressed this and improves how probability distributions are used.
